[package]
name = "capra-planner"
version = "0.1.0"
authors = ["Anson <git@anson-cheung.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
actix-cors = "0.2.0"
serde = "1.0.106"
capra = {path="../capra"}
time = "0.2.9"
thiserror = "1.0.19"
