-- This file should undo anything in `up.sql`
DROP TABLE IF EXISTS Users;

DROP TABLE IF EXISTS ZHLSettings;

DROP TABLE IF EXISTS GasPlanSettings;

DROP TABLE IF EXISTS Dives;

DROP TABLE IF EXISTS VPMSettings;

DROP TABLE IF EXISTS Segments;

DROP TABLE IF EXISTS Gases;

DROP TABLE IF EXISTS Tissues;
